/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package deu.hms.management;

import deu.hms.room.RoomInfoLoad;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.io.File;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author choun
 */
public class RoomManagementFrame extends javax.swing.JFrame {

    String paths = System.getProperty("user.dir");
    File roominfoFile = new File(paths + "/RoomInfo.txt");

    /**
     * Creates new form RoomInfoFrame
     */
    public RoomManagementFrame() {
        initComponents();
        loadRoomInfo();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        roomInfoTable = new javax.swing.JTable();
        saveButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        jLabel1.setText("객실 정보");

        roomInfoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "층수", "등급", "가격"
            }
        ));
        jScrollPane1.setViewportView(roomInfoTable);

        saveButton.setText("저장");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("삭제");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        closeButton.setText("닫기");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        jButton1.setText("등록");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(177, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(deleteButton)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if (roomInfoTable.getCellEditor() != null) {
            roomInfoTable.getCellEditor().stopCellEditing();
        }
        
        JPanel inputPanel = new JPanel();
        inputPanel.setLayout(new BoxLayout(inputPanel, BoxLayout.Y_AXIS));
        
        JLabel reasonLabel = new JLabel("수정사항 및 이유를 입력하시오.");
        reasonLabel.setFont(new Font("맑은 고딕", Font.BOLD, 14));
        reasonLabel.setAlignmentX(Component.CENTER_ALIGNMENT);
        inputPanel.add(reasonLabel);
        
        JTextField reasonField = new JTextField();
        reasonField.setPreferredSize(new Dimension(300, 50));
        inputPanel.add(reasonField );
        
        boolean validInput = false;

        while (!validInput) {
            int result = JOptionPane.showConfirmDialog(this, inputPanel, "수정 및 저장", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
            if (result == JOptionPane.OK_OPTION) {
                String reason = reasonField.getText().trim();
                if (reason.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "내용 입력하세요.", "Error", JOptionPane.ERROR_MESSAGE);
                    continue;
                }
                try {
                    new ChangeSaveFile(roomInfoTable, roominfoFile);
                    JOptionPane.showMessageDialog(null, "변경사항이 저장되었습니다." );
                    validInput = true;
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "내용을 입력하세요.", "Error", JOptionPane.ERROR_MESSAGE);
                    continue;
                }
            }
            else{
                break;
            }
        }
        
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int selectedRow = roomInfoTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "삭제할 행을 선택하세요.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        DefaultTableModel model = (DefaultTableModel) roomInfoTable.getModel();
        model.removeRow(selectedRow);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JPanel inputPanel = new JPanel();
        inputPanel.setLayout(new BoxLayout(inputPanel, BoxLayout.Y_AXIS));

        JLabel floorLabel = new JLabel("층수");
        floorLabel.setFont(new Font("맑은 고딕", Font.BOLD, 16));
        floorLabel.setAlignmentX(Component.CENTER_ALIGNMENT);
        inputPanel.add(floorLabel);

        JTextField floorLabelField = new JTextField();
        floorLabelField.setPreferredSize(new Dimension(300, 50));
        inputPanel.add(floorLabelField);

        JLabel ratingLabel = new JLabel("등급");
        ratingLabel.setFont(new Font("맑은 고딕", Font.BOLD, 16));
        ratingLabel.setAlignmentX(Component.CENTER_ALIGNMENT);
        inputPanel.add(ratingLabel);

        JTextField ratingLabelField = new JTextField();
        ratingLabelField.setPreferredSize(new Dimension(300, 50));
        inputPanel.add(ratingLabelField);

        JLabel priceLabel = new JLabel("가격");
        priceLabel.setFont(new Font("맑은 고딕", Font.BOLD, 16));
        priceLabel.setAlignmentX(Component.CENTER_ALIGNMENT);
        inputPanel.add(priceLabel);

        JTextField priceField = new JTextField();
        priceField.setPreferredSize(new Dimension(300, 50));
        inputPanel.add(priceField);

        boolean validInput = false;

        while (!validInput) {
            int result = JOptionPane.showConfirmDialog(this, inputPanel, "객실 정보 등록", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
            if (result == JOptionPane.OK_OPTION) {
                String floor = floorLabelField.getText().trim();
                String rate = ratingLabelField.getText().trim();
                String priceString = priceField.getText().trim();

                if (floor.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "층수를 입력하세요.", "Error", JOptionPane.ERROR_MESSAGE);
                    continue;
                }
                if (rate.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "등급을 입력하세요.", "Error", JOptionPane.ERROR_MESSAGE);
                    continue;
                }
                if (priceString.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "가격을 입력하세요.", "Error", JOptionPane.ERROR_MESSAGE);
                    continue;
                }
                try {
                    int price = Integer.parseInt(priceString);
                    DefaultTableModel model = (DefaultTableModel) roomInfoTable.getModel();
                    model.addRow(new Object[]{floor, rate, price});
                    validInput = true;
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "올바른 가격을 입력하세요.", "Error", JOptionPane.ERROR_MESSAGE);
                    continue;
                }
            } else {
                break;
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void loadRoomInfo() {
        DefaultTableModel roominfoModel = (DefaultTableModel) roomInfoTable.getModel();
        new RoomInfoLoad(roominfoModel);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomManagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomManagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomManagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomManagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomManagementFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable roomInfoTable;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
